default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: lutok_web_dev

test:
  <<: *default
  database: lutok_web_test

production:
  <<: *default
  database: lutok_web
